/**
 * Label dictionary for the Word export structure (section titles, table
 * headers, sub-labels, footers). Record *data* (names, parts, services,
 * notes) is never translated — only the report chrome. Default is English,
 * matching the original Word export behavior; Arabic is opt-in via the
 * Word export template settings.
 */
import type { WordLabelLang } from "./wordExportTemplate";

const en = {
  clientReport: "Client Report",
  costReport: "Maintenance Cost Report",
  serviceReportFooter: "Service Report",
  generated: "Generated",
  period: "Period",
  visitDate: "Visit Date",
  scheduled: "Scheduled",
  requested: "Requested",
  resolved: "Resolved",
  unresolved: "Unresolved",
  routine: "Routine",
  companyProfile: "Company Profile",
  taxNo: "Tax No.",
  email: "Email",
  location: "Location",
  machineOwnership: "Machine Ownership",
  coffeeConsumption: "Coffee consumption",
  maintenanceTimes: "Maintenance times",
  keyContacts: "Key Contacts",
  contacts: "Contacts",
  name: "Name",
  position: "Position",
  phone: "Phone",
  assignedStaff: "Assigned Staff",
  maintenanceLog: "Maintenance Log",
  mainOfficeMaintenance: "Main Office Maintenance",
  performanceSummary: "Performance Summary",
  totalVisits: "Total Visits",
  resolutionRate: "Resolution Rate",
  spareParts: "Spare Parts",
  netCost: "Net Cost",
  totalCost: "Total Cost",
  company: "Company",
  client: "Client",
  techPerformance: "Technician Performance",
  technician: "Technician",
  visits: "Visits",
  avgRating: "Avg Rating",
  partsUsed: "Parts Used",
  zones: "Zones",
  logisticsTitle: "Logistics — Machine Transport & Replacement",
  operation: "Operation",
  category: "Category",
  status: "Status",
  openDate: "Open Date",
  closeDate: "Close Date",
  rental: "Rental",
  maintenance: "Maintenance",
  pickupDeliver: "Pickup & Deliver",
  deliverOnly: "Deliver Only",
  pickupOnly: "Pickup Only",
  costBreakdown: "Cost Breakdown",
  item: "Item",
  detail: "Detail",
  total: "Total",
  categoryTotal: "Category Total",
  clientStaff: "Client Staff",
  zone: "Zone",
  paidBy: "Paid By",
  midos: "Midos",
  dailyLease: "Daily Lease",
  nextVisit: "Next Visit",
  machines: "Machines",
  issues: "Issues",
  partsReplaced: "Parts Replaced",
  servicesPerformed: "Services Performed",
  recordTotal: "Record Total",
  recommendations: "Recommendations",
  notes: "Notes",
  supervisors: "Supervisors",
  followUpVisits: "Follow-up Visits",
  beforePhotos: "Before Photos",
  afterPhotos: "After Photos",
  legacyPhotos: "Photos",
  batchSummary: "Batch Summary",
  records: "Records",
  companies: "Companies",
  branches: "Branches",
  selection: "Selection",
  recordsSummary: "Records Summary",
  date: "Date",
  branch: "Branch",
  type: "Type",
  cost: "Cost",
  missingDataForm: "Missing Data Form",
  missingDataInstructions: "Instructions: fill in the fields below with the required data, then send the file back.",
  companyInfo: "Company Information",
  branchInfo: "Branch Information",
  endOfMissingDataForm: "End of Missing Data Form",
  maintenanceVisitReport: "Maintenance Visit Report",
  internalUseDocument: "Internal Use Document",
  clientAndVisitInfo: "Client & Visit Info",
  companyName: "Company Name",
  contactName: "Contact Name",
  contactPhone: "Contact Phone",
  workPerformed: "Work Performed",
  servicesDone: "Services Performed",
  customPartsTitle: "Custom Parts / Additional Services",
  qty: "Qty",
  clientPaid: "Client Paid",
  issuesNotes: "Identified Issues, Recommendations & Notes",
  endOfWorkOrder: "End of Work Order",
  frequentlyReplaced: "Most Frequently Replaced",
  otherParts: "Other Parts",
  visitSummary: "Visit Summary",
  mainOffice: "Main Office",
  companyReport: "Company Report",
  branchReport: "Branch Report",
  bulkExport: "Bulk Export",
  mixedFleet: "Mixed fleet",
  clientMachine: "Client Machine",
  ours: "Ours",
  notSpecified: "Not specified",
  of: "of",
  allCostsIncluded: "all costs included",
} as const;

type LabelKey = keyof typeof en;

const ar: Record<LabelKey, string> = {
  clientReport: "تقرير العميل",
  costReport: "تقرير تكاليف الصيانة",
  serviceReportFooter: "تقرير الخدمة",
  generated: "تاريخ الإنشاء",
  period: "الفترة",
  visitDate: "تاريخ الزيارة",
  scheduled: "مجدولة",
  requested: "مطلوبة",
  resolved: "تم الحل",
  unresolved: "لم يتم الحل",
  routine: "روتينية",
  companyProfile: "بيانات الشركة",
  taxNo: "الرقم الضريبي",
  email: "البريد الإلكتروني",
  location: "الموقع",
  machineOwnership: "ملكية الماكينات",
  coffeeConsumption: "استهلاك القهوة",
  maintenanceTimes: "مواعيد الصيانة",
  keyContacts: "جهات الاتصال الرئيسية",
  contacts: "جهات الاتصال",
  name: "الاسم",
  position: "المنصب",
  phone: "الهاتف",
  assignedStaff: "الطاقم المكلف",
  maintenanceLog: "سجل الصيانة",
  mainOfficeMaintenance: "صيانة المكتب الرئيسي",
  performanceSummary: "ملخص الأداء",
  totalVisits: "إجمالي الزيارات",
  resolutionRate: "نسبة الحل",
  spareParts: "قطع الغيار",
  netCost: "صافي التكلفة",
  totalCost: "إجمالي التكلفة",
  company: "الشركة",
  client: "العميل",
  techPerformance: "أداء الفنيين",
  technician: "الفني",
  visits: "الزيارات",
  avgRating: "متوسط التقييم",
  partsUsed: "قطع الغيار المستخدمة",
  zones: "المناطق",
  logisticsTitle: "اللوجستيات — نقل واستبدال الماكينات",
  operation: "العملية",
  category: "الفئة",
  status: "الحالة",
  openDate: "تاريخ الفتح",
  closeDate: "تاريخ الإغلاق",
  rental: "الإيجار",
  maintenance: "الصيانة",
  pickupDeliver: "استلام وتسليم",
  deliverOnly: "تسليم فقط",
  pickupOnly: "استلام فقط",
  costBreakdown: "تفاصيل التكاليف",
  item: "البند",
  detail: "التفاصيل",
  total: "الإجمالي",
  categoryTotal: "إجمالي الفئة",
  clientStaff: "موظف العميل",
  zone: "المنطقة",
  paidBy: "الدفع بواسطة",
  midos: "ميدوس",
  dailyLease: "الإيجار اليومي",
  nextVisit: "الزيارة القادمة",
  machines: "الماكينات",
  issues: "المشاكل",
  partsReplaced: "قطع الغيار المستبدلة",
  servicesPerformed: "الخدمات المنفذة",
  recordTotal: "إجمالي الزيارة",
  recommendations: "التوصيات",
  notes: "ملاحظات",
  supervisors: "المشرفون",
  followUpVisits: "زيارات المتابعة",
  beforePhotos: "صور قبل",
  afterPhotos: "صور بعد",
  legacyPhotos: "صور",
  batchSummary: "ملخص الدفعة",
  records: "السجلات",
  companies: "الشركات",
  branches: "الفروع",
  selection: "الاختيار",
  recordsSummary: "ملخص السجلات",
  date: "التاريخ",
  branch: "الفرع",
  type: "النوع",
  cost: "التكلفة",
  missingDataForm: "نموذج استكمال البيانات",
  missingDataInstructions: "تعليمات: يرجى ملء الحقول التالية بالبيانات المطلوبة وإعادة إرسال الملف.",
  companyInfo: "بيانات الشركة",
  branchInfo: "بيانات الفرع",
  endOfMissingDataForm: "نهاية نموذج استكمال البيانات",
  maintenanceVisitReport: "تقرير زيارة الصيانة",
  internalUseDocument: "مستند للاستخدام الداخلي",
  clientAndVisitInfo: "بيانات العميل والزيارة",
  companyName: "اسم الشركة",
  contactName: "اسم جهة الاتصال",
  contactPhone: "هاتف جهة الاتصال",
  workPerformed: "الأعمال المنفذة",
  servicesDone: "الخدمات المنفذة",
  customPartsTitle: "قطع غيار / خدمات إضافية",
  qty: "الكمية",
  clientPaid: "دفع العميل",
  issuesNotes: "المشاكل والتوصيات والملاحظات",
  endOfWorkOrder: "نهاية أمر العمل",
  frequentlyReplaced: "الأكثر استبدالاً",
  otherParts: "قطع غيار أخرى",
  visitSummary: "ملخص الزيارات",
  mainOffice: "المكتب الرئيسي",
  companyReport: "تقرير الشركة",
  branchReport: "تقرير الفرع",
  bulkExport: "تصدير متعدد",
  mixedFleet: "أسطول مختلط",
  clientMachine: "ماكينة العميل",
  ours: "خاصة بنا",
  notSpecified: "غير محدد",
  of: "من",
  allCostsIncluded: "تشمل جميع التكاليف",
};

const dictionaries: Record<WordLabelLang, Record<LabelKey, string>> = { en, ar };

/** Translate a structural label for the given report label language. */
export const t = (lang: WordLabelLang, key: LabelKey): string => dictionaries[lang][key];

export type { LabelKey };
