-- Migration: Create logistics_operations and company_machines tables
-- Phase 01: Machine Logistics Workflow

-- 1. Company Machines (replacement machine inventory)
CREATE TABLE IF NOT EXISTS company_machines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('coffee', 'grinder', 'other')),
  machine_type TEXT CHECK (machine_type IN ('manual', 'automatic', 'semi_automatic')),
  status TEXT DEFAULT 'available' CHECK (status IN ('available', 'in_use', 'damaged', 'lost')),
  monthly_rental_price NUMERIC(10,2) CHECK (monthly_rental_price IS NULL OR monthly_rental_price >= 0),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Logistics Operations
CREATE TABLE IF NOT EXISTS logistics_operations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  opened_by_record_id BIGINT,
  closed_by_record_id BIGINT,
  operation_type TEXT NOT NULL CHECK (operation_type IN ('pickup_and_deliver', 'deliver_only', 'pickup_only')),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  machine_category TEXT CHECK (machine_category IN ('coffee', 'grinder', 'other')),
  machine_ownership TEXT CHECK (machine_ownership IN ('customer', 'company')),
  machine_type TEXT CHECK (machine_type IN ('manual', 'automatic', 'semi_automatic')),
  replacement_machine_id BIGINT REFERENCES company_machines(id) ON DELETE SET NULL,
  monthly_rental_price NUMERIC(10,2) CHECK (monthly_rental_price IS NULL OR monthly_rental_price >= 0),
  daily_rental_price NUMERIC(10,2) GENERATED ALWAYS AS (
    CASE WHEN monthly_rental_price IS NOT NULL
      THEN ROUND(monthly_rental_price / 30.0, 2)
      ELSE NULL
    END
  ) STORED,
  rental_duration_days INTEGER,
  rental_duration_hours INTEGER,
  rental_duration_minutes INTEGER,
  billable_days INTEGER,
  total_rental_cost NUMERIC(10,2),
  pickup_cost NUMERIC(10,2) DEFAULT 0 CHECK (pickup_cost >= 0),
  return_cost NUMERIC(10,2) DEFAULT 0 CHECK (return_cost >= 0),
  total_logistics_cost NUMERIC(10,2) GENERATED ALWAYS AS (
    COALESCE(total_rental_cost, 0) + COALESCE(pickup_cost, 0) + COALESCE(return_cost, 0)
  ) STORED,
  internal_notes TEXT,
  created_by UUID REFERENCES auth.users(id),
  closed_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Indexes
CREATE INDEX IF NOT EXISTS idx_logistics_operations_customer_id ON logistics_operations(customer_id);

-- 4. Row Level Security
ALTER TABLE company_machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE logistics_operations ENABLE ROW LEVEL SECURITY;

-- Company machines: authenticated users can read
CREATE POLICY "Authenticated users can read company_machines"
  ON company_machines FOR SELECT
  USING (auth.role() = 'authenticated');

-- Company machines: authenticated users can insert
CREATE POLICY "Authenticated users can insert company_machines"
  ON company_machines FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Company machines: authenticated users can update (placeholder — restrict to admin role when available)
CREATE POLICY "Authenticated users can update company_machines"
  ON company_machines FOR UPDATE
  USING (auth.role() = 'authenticated');

-- Company machines: authenticated users can delete (placeholder — restrict to admin role when available)
CREATE POLICY "Authenticated users can delete company_machines"
  ON company_machines FOR DELETE
  USING (auth.role() = 'authenticated');

-- Logistics operations: authenticated users can read
CREATE POLICY "Authenticated users can read logistics_operations"
  ON logistics_operations FOR SELECT
  USING (auth.role() = 'authenticated');

-- Logistics operations: authenticated users can insert
CREATE POLICY "Authenticated users can insert logistics_operations"
  ON logistics_operations FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Logistics operations: authenticated users can update (scoped to creating user)
CREATE POLICY "Authenticated users can update logistics_operations"
  ON logistics_operations FOR UPDATE
  USING (auth.role() = 'authenticated' AND created_by = auth.uid());
