-- Migration: Create machine_names table
-- Stores the user's saved machine names/brands. These appear as suggestions
-- in the logistics machine operations form's "Machine Name" fields and are
-- managed from the company machines settings page.

CREATE TABLE IF NOT EXISTS machine_names (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Case-insensitive uniqueness: "La Marzocco" and "la marzocco" are the same name.
CREATE UNIQUE INDEX IF NOT EXISTS idx_machine_names_name_unique ON machine_names (LOWER(name));

-- Index for fast alphabetical suggestion lookups
CREATE INDEX IF NOT EXISTS idx_machine_names_name ON machine_names(name);

-- Row Level Security
ALTER TABLE machine_names ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read machine_names" ON machine_names;
CREATE POLICY "Authenticated users can read machine_names"
  ON machine_names FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can insert machine_names" ON machine_names;
CREATE POLICY "Authenticated users can insert machine_names"
  ON machine_names FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can update machine_names" ON machine_names;
CREATE POLICY "Authenticated users can update machine_names"
  ON machine_names FOR UPDATE
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can delete machine_names" ON machine_names;
CREATE POLICY "Authenticated users can delete machine_names"
  ON machine_names FOR DELETE
  USING (auth.role() = 'authenticated');
